apiVersion: "oathkeeper.ory.sh/v1alpha1"
kind: Rule
metadata:
  name: {{ include "vapor-proxy.fullname" . }}-access-rules
  namespace: {{ .Values.rules.namespace }}
spec:
  upstream:
    url: {{ include "vapor-proxy.url" . }}
    preserveHost: {{ .Values.rules.upstream.preserveHost }}
    {{- if .Values.rules.upstream.stripPath }}
    stripPath: {{ .Values.rules.upstream.stripPath }}
    {{- end }}
  match:
    url: {{ .Values.rules.match.url }}
    methods:
      {{- range .Values.rules.match.methods }}
      - {{ . }}
      {{- end }}
  authenticators:
    {{- range .Values.rules.authenticators }}
    - handler: {{ . | quote }}
    {{- end }}
  mutators:
    {{- range .Values.rules.mutators }}
    - handler: {{ . | quote }}
    {{- end }}
  authorizer:
    handler: {{ .Values.rules.authorizer }}

{{- if .Values.extraRules }}
---
apiVersion: "oathkeeper.ory.sh/v1alpha1"
kind: Rule
metadata:
  name: {{ include "vapor-proxy.fullname" . }}-extra-access-rules
  namespace: {{ .Values.extraRules.namespace }}
spec:
  upstream:
    url: {{ include "vapor-proxy.url" . }}
    preserveHost: {{ .Values.extraRules.upstream.preserveHost }}
    {{- if .Values.extraRules.upstream.stripPath }}
    stripPath: {{ .Values.extraRules.upstream.stripPath }}
    {{- end }}
  match:
    url: {{ .Values.extraRules.match.url }}
    methods:
      {{- range .Values.extraRules.match.methods }}
      - {{ . }}
      {{- end }}
  authenticators:
    {{- range .Values.extraRules.authenticators }}
    - handler: {{ . | quote }}
    {{- end }}
  mutators:
    {{- range .Values.extraRules.mutators }}
    - handler: {{ . | quote }}
    {{- end }}
  authorizer:
    handler: {{ .Values.extraRules.authorizer }}
{{- end }}