apiVersion: v1
kind: Service
metadata:
  name: {{ include "vapor-proxy.fullname" . }}
  labels:
    {{- include "vapor-proxy.labels" . | nindent 4 }}
  annotations:
    kuma.io/mesh: {{ .Values.mesh }}
    {{ .Values.service.port }}.service.kuma.io/protocol: "http"
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vapor-proxy.selectorLabels" . | nindent 4 }}
